### ISSUE TITLE
Morning Review - 15/12/2021

### ISSUE THREAD

**Issue by John-Arboleda** [yigitm/leaderboard#2]
There is no need to use form tags when you are using Javascript for the log of new scores and refresh the page
https://github.com/yigitm/leaderboard/blob/80871c2c8db4b3d61bbfb42754efc0217b1ebbf7/src/index.html#L13-L16

https://github.com/yigitm/leaderboard/blob/80871c2c8db4b3d61bbfb42754efc0217b1ebbf7/src/index.html#L29-L33

**Comment by yigitm** [comment]
Thank you. Form tags are removed.
